name: 'Close stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          #repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 4 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 4 days with no activity.'
          days-before-pr-stale: 1
          days-before-pr-close: 1
